# encoding: utf-8
objs=[
  {"id"=>1, :key=>"d_KnotSize", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"套型"},
  {"id"=>2, "key"=>"d_OwnerIDType", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"证件类型"},
  {"id"=>3, "key"=>"", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"收据类型"},
  {"id"=>4, "key"=>"", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"文件类型"},
  {"id"=>70, "key"=>"d_OwnerWay", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"所属行业"},
  {"id"=>71, "key"=>"d_CompanyType", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"单位性质"},
  {"id"=>25, "key"=>"d_UseType", "IsSystem"=>false, "Memo"=>"qweqew", "TypeName"=>"设计用途"},
  {"id"=>26, "key"=>"d_HousePorperty", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"产别"},
  {"id"=>27, "key"=>"d_Structure", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"结构"},
  {"id"=>28, "key"=>"d_BuyHouseType", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"产权来源"},
  {"id"=>29, "key"=>"d_OwnerType", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"业主类型"},
  {"id"=>30, "key"=>"d_OwnerState", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"业主状态"},
  {"id"=>31, "key"=>"d_HouseState", "IsSystem"=>false, "Memo"=>"", "TypeName"=>"房屋状态"},
  {"id"=>32, "key"=>"d_TdXingzhi", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"土地性质"},
  {"id"=>33, "key"=>"", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"四墙类型"},
  {"id"=>37, "key"=>"d_BizSource", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"业务来源"},
  {"id"=>38, "key"=>"d_CardType", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"房屋权证类型"},
  {"id"=>42, "key"=>"d_DroitType", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"权利种类"},
  {"id"=>47, "key"=>"d_mdptel", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"抵押权人"},
  {"id"=>48, "key"=>"", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"文件来源"},
  {"id"=>49, "key"=>"", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"文件类型"},
  {"id"=>50, "key"=>"", "IsSystem"=>false, "Memo"=>"费率设定使用", "TypeName"=>"查档类型"},
  {"id"=>52, "key"=>"d_EvaluateWay", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"评估方法"},
  {"id"=>53, "key"=>"d_Diquleibie", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"地区类别"},
  {"id"=>56, "key"=>"d_MoperKind", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"抵押业务种类"},
  {"id"=>57, "key"=>"d_DataSource", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"项目数据来源"},
  {"id"=>58, "key"=>"d_ModifyType", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"变更类型"},
  {"id"=>59, "key"=>"d_ApplyType", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"申请类型"},
  {"id"=>60, "key"=>"d_EnsureVithRent", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"申请配租类别"},
  {"id"=>61, "key"=>"", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"符号"},
  {"id"=>62, "key"=>"d_BuildType", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"楼幢类型"},
  {"id"=>64, "key"=>"d_HouseType", "IsSystem"=>false, "Memo"=>"", "TypeName"=>"房屋类型"},
  {"id"=>65, "key"=>"", "IsSystem"=>false, "Memo"=>"", "TypeName"=>"查档范围"},
  {"id"=>66, "key"=>"d_fshuseType", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"供役地房屋利用方式"},
  {"id"=>67, "key"=>"d_Relation", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"与产权人关系"},
  {"id"=>68, "key"=>"d_PoolMemo", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"共有情况"},
  {"id"=>69, "key"=>"", "IsSystem"=>false, "Memo"=>"", "TypeName"=>"费率码表"},
  {"id"=>39, "key"=>"", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"项目权证类型"},
  {"id"=>10, "key"=>"d_job", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"职位"},
  {"id"=>23, "key"=>"", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"身份证"},
  {"id"=>43, "key"=>"", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"项目状态"},
  {"id"=>51, "key"=>"", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"房屋数据来源"},
  {"id"=>54, "key"=>"d_PayType", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"付款方式"},
  {"id"=>55, "key"=>"d_LandGetMode", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"土地取得方式"},
  {"id"=>72, "key"=>"d_ContractState", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"合同状态"},
  {"id"=>73, "key"=>"", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"房屋账户状态"},
  {"id"=>74, "key"=>"d_BizSource", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"业务来源"},
  {"id"=>75, "key"=>"d_Education", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"学历"},
  {"id"=>77, "key"=>"", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"支付方式"},
  {"id"=>78, "key"=>"d_ApplyUnitType", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"申请单位类型"},
  {"id"=>79, "key"=>"d_Nationality", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"国籍"},
  {"id"=>80, "key"=>"d_Domicile", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"户籍所在地"},
  {"id"=>81, "key"=>"d_annex", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"附件"},
  {"id"=>1357, "key"=>"", "IsSystem"=>false, "Memo"=>"", "TypeName"=>"变更原因"},
  {"id"=>82, "key"=>"", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"维修资金业务来源"},
  {"id"=>83, "key"=>"d_OperType", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"操作类型"},
  {"id"=>84, "key"=>"", "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"退款原因"},
  {"id"=>2628, "key"=>"", "IsSystem"=>false, "Memo"=>"", "TypeName"=>"地类用途"},
  {"id"=>76, "key"=>"", "IsSystem"=>false, "Memo"=>"", "TypeName"=>"证书级别"}]

Dgwordbooktype.delete_all              
for ha in objs
  obj = Dgwordbooktype.new
  obj.send(:attributes=, ha, false)
  obj.save
end
                
