# encoding: utf-8
objs=[
  {"id"=>1, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"套型"},
  {"id"=>2, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"证件类型"},
  {"id"=>3, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"收据类型"},
  {"id"=>4, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"文件类型"},
  {"id"=>70, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"所属行业"},
  {"id"=>71, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"单位性质"},
  {"id"=>25, "IsSystem"=>false, "Memo"=>"qweqew", "TypeName"=>"设计用途"},
  {"id"=>26, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"产别"},
  {"id"=>27, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"结构"},
  {"id"=>28, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"产权来源"},
  {"id"=>29, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"业主类型"},
  {"id"=>30, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"业主状态"},
  {"id"=>31, "IsSystem"=>false, "Memo"=>"", "TypeName"=>"房屋状态"},
  {"id"=>32, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"土地性质"},
  {"id"=>33, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"四墙类型"},
  {"id"=>37, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"业务来源"},
  {"id"=>38, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"房屋权证类型"},
  {"id"=>42, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"权利种类"},
  {"id"=>47, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"抵押权人"},
  {"id"=>48, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"文件来源"},
  {"id"=>49, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"文件类型"},
  {"id"=>50, "IsSystem"=>false, "Memo"=>"费率设定使用", "TypeName"=>"查档类型"},
  {"id"=>52, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"评估方法"},
  {"id"=>53, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"地区类别"},
  {"id"=>56, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"抵押业务种类"},
  {"id"=>57, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"项目数据来源"},
  {"id"=>58, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"变更类型"},
  {"id"=>59, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"申请类型"},
  {"id"=>60, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"申请配租类别"},
  {"id"=>61, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"符号"},
  {"id"=>62, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"楼幢类型"},
  {"id"=>64, "IsSystem"=>false, "Memo"=>"", "TypeName"=>"房屋类型"},
  {"id"=>65, "IsSystem"=>false, "Memo"=>"", "TypeName"=>"查档范围"},
  {"id"=>66, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"供役地房屋利用方式"},
  {"id"=>67, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"与产权人关系"},
  {"id"=>68, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"共有情况"},
  {"id"=>69, "IsSystem"=>false, "Memo"=>"", "TypeName"=>"费率码表"},
  {"id"=>39, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"项目权证类型"},
  {"id"=>10, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"职位"},
  {"id"=>23, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"身份证"},
  {"id"=>43, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"项目状态"},
  {"id"=>51, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"房屋数据来源"},
  {"id"=>54, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"付款方式"},
  {"id"=>55, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"土地取得方式"},
  {"id"=>72, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"合同状态"},
  {"id"=>73, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"房屋账户状态"},
  {"id"=>74, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"业务来源"},
  {"id"=>75, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"学历"},
  {"id"=>77, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"支付方式"},
  {"id"=>78, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"申请单位类型"},
  {"id"=>79, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"国籍"},
  {"id"=>80, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"户籍所在地"},
  {"id"=>81, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"附件"},
  {"id"=>1357, "IsSystem"=>false, "Memo"=>"", "TypeName"=>"变更原因"},
  {"id"=>82, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"维修资金业务来源"},
  {"id"=>83, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"操作类型"},
  {"id"=>84, "IsSystem"=>false, "Memo"=>nil, "TypeName"=>"退款原因"},
  {"id"=>2628, "IsSystem"=>false, "Memo"=>"", "TypeName"=>"地类用途"},
  {"id"=>76, "IsSystem"=>false, "Memo"=>"", "TypeName"=>"证书级别"}]

Dgwordbooktype.delete_all              
for ha in objs
  obj = Dgwordbooktype.new
  obj.send(:attributes=, ha, false)
  obj.save
end
                
